Feature crear editar usuario
dav793/proyecto-ng-blog pull request #5
Opened 2019-03-05 04:14 UTC by felipeSolisJimenez

Finalizados componentes para crear-Editar usuario y login
Se avanzó en la vista para ver perfil de un usuario

2019-03-06 00:43 UTC, dav793 commented on src/app/login/login.component.ts
> +import { Component, OnInit } from '@angular/core';
Este branch es el del issue de editar/crear usuario (https://cvfdev.atlassian.net/browse/BP-9), pero este file tiene que ver con login, que es otro issue diferente (https://cvfdev.atlassian.net/browse/BP-21). Por esta vez se lo voy a aceptar, pero en el futuro vamos a requerir que los cambios estén bien aislados en sus branches correspondientes.

2019-03-06 00:44 UTC, dav793 commented on src/app/user/user-view/user-view.component.ts
> +import { Component, OnInit } from '@angular/core';
Este branch es el del issue de editar/crear usuario (https://cvfdev.atlassian.net/browse/BP-9), pero este file tiene que ver el perfil de usuario, que es otro issue diferente (https://cvfdev.atlassian.net/browse/BP-10). Por esta vez se lo voy a aceptar, pero en el futuro vamos a requerir que los cambios estén bien aislados en sus branches correspondientes.

2019-03-06 00:48 UTC, dav793 commented on src/app/app.routing.ts
> +      { path: 'edit', component: UserFormComponent }
Dónde está el parámetro del id del usuario que se está editando? Cómo sabe cuál usuario editar?

2019-03-06 00:54 UTC, dav793 commented on src/app/user/user-form/user-form.component.ts
> +  checkLoggedUser() {
Este componente no debería seleccionar el usuario loggeado. Escoger cuál usuario se está editando no es responsabilidad de este componente. Debería escoger el usuario según el userId que reciba del router. Esto es necesario para promover la reusabilidad de su componente.

2019-03-06 00:58 UTC, dav793 commented on src/app/nav/nav.component.html
> +      <a class="nav-link" [routerLink]="['/users/create']">Regístrese</a>
El nav debe presentar "Registrese" si no hay usuario loggeado, o "Nombre del usuario" si hay usuario loggeado (en cuyo caso debe llevar a la ruta /users/edit/:id, no /users/create. Actualmente solo muestra "Registrese".

2019-03-06 01:00 UTC, dav793 requested changes
Para aprovar este PR, por favor haga los cambios que le pedí mediante comentarios aquí.

2019-03-06 03:03 UTC, felipeSolisJimenez commented on src/app/login/login.component.ts
> +import { Component, OnInit } from '@angular/core';
Si está bien

2019-03-06 03:09 UTC, felipeSolisJimenez commented on src/app/app.routing.ts
> +      { path: 'edit', component: UserFormComponent }
Solo puede editar el usuario Logueado, voy a agregarle el parámetro id a la ruta

2019-03-06 03:09 UTC, felipeSolisJimenez commented on src/app/user/user-form/user-form.component.ts
> +  checkLoggedUser() {
Voy a corregirlo

2019-03-06 03:10 UTC, felipeSolisJimenez commented on src/app/nav/nav.component.html
> +      <a class="nav-link" [routerLink]="['/users/create']">Regístrese</a>
Voy a corregirlo

2019-03-06 21:56 UTC, felipeSolisJimenez commented on src/app/app.routing.ts
> +      { path: 'edit', component: UserFormComponent }
Corregido!!

2019-03-06 21:56 UTC, felipeSolisJimenez commented on src/app/user/user-form/user-form.component.ts
> +  checkLoggedUser() {
Corregido!!

2019-03-07 01:46 UTC, felipeSolisJimenez commented on src/app/nav/nav.component.html
> +      <a class="nav-link" [routerLink]="['/users/create']">Regístrese</a>
Listo!!

2019-03-09 02:45 UTC, dav793 approved these changes

2019-03-09 02:47 UTC, merged