Feature ver usuario
dav793/proyecto-ng-blog pull request #6
Opened 2019-03-27 00:09 UTC by felipeSolisJimenez

2019-03-28 16:41 UTC, dav793 commented on src/app/user/user-view/user-view.component.ts
> +  getUserToShow() {
Es un detalle muy menor, pero podríamos escoger un mejor nombre para esta función. getUserToShow implica como que la función se encarga de rendering, pero no es exactamente así. La función obtiene el usuario del servidor y lo guarda en el componente, eso es más como un setup. Entonces un mejor nombre podría ser como setupUser o loadUser.

2019-03-28 16:44 UTC, dav793 commented on src/app/user/user.service.ts
> +    allPosts.forEach(element => {
Como consejo, aquí puede lograr lo mismo con 'filter', y se ve mas limpio y fácil de interpretar. Ejemplo:

`let postsFromUser = allPosts.filter(post => post.author === userId)`

2019-03-28 17:05 UTC, dav793 requested changes
Excelente! Nada más le dejo un par de cambios menores, para que mejorando aún más la forma de programar, pero todo muy bien! :thumbsup::thumbsup:

2019-03-28 18:29 UTC, felipeSolisJimenez commented on src/app/user/user-view/user-view.component.ts
> +  getUserToShow() {
Corregido

2019-04-01 20:47 UTC, dav793 approved these changes

2019-04-02 04:09 UTC, merged